name: Test Zitadel OAuth

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-google-oauth:
    runs-on: ubuntu-latest
    env:
      ##########################################################################
      # App Config
      ##########################################################################
      NEXT_PUBLIC_URL: "http://localhost:3000"
      DATABASE_URI: "file:./payload-oauth2.db"
      PAYLOAD_SECRET: "hellohereisasecretforyou"

      ##########################################################################
      # Google OAuth Config
      ##########################################################################
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      ##########################################################################
      # Test Config
      ##########################################################################
      # Optional: Set to "true" to run test browser in headless mode
      HEADLESS: true

      ##########################################################################
      # Google Test Account
      ##########################################################################
      # Required: Google Test Account Email
      GOOGLE_TEST_EMAIL: ${{ secrets.GOOGLE_TEST_EMAIL }}

      # Required: Google Test Account Password
      GOOGLE_TEST_PASSWORD: ${{ secrets.GOOGLE_TEST_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: |
          pnpx puppeteer browsers install chrome
      - run: pnpm install
      - run: pnpm test:google
  test-zitadel-oauth:
    runs-on: ubuntu-latest
    env:
      ##########################################################################
      # App Config
      ##########################################################################
      NEXT_PUBLIC_URL: "http://localhost:3000"
      DATABASE_URI: "file:./payload-oauth2.db"
      PAYLOAD_SECRET: "hellohereisasecretforyou"

      ##########################################################################
      # Zitadel OAuth Config
      ##########################################################################
      ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
      ZITADEL_CLIENT_SECRET: ${{ secrets.ZITADEL_CLIENT_SECRET }}
      ZITADEL_TOKEN_ENDPOINT: ${{ secrets.ZITADEL_TOKEN_ENDPOINT }}
      ZITADEL_AUTHORIZATION_URL: ${{ secrets.ZITADEL_AUTHORIZATION_URL }}
      ZITADEL_USERINFO_ENDPOINT: ${{ secrets.ZITADEL_USERINFO_ENDPOINT }}

      ##########################################################################
      # Test Config
      ##########################################################################
      # Optional: Set to "true" to run test browser in headless mode
      HEADLESS: true

      ##########################################################################
      # Zitadel Test Account
      ##########################################################################
      # Required: Zitadel Test Account Email
      ZITADEL_TEST_EMAIL: ${{ secrets.ZITADEL_TEST_EMAIL }}

      # Required: Zitadel Test Account Password
      ZITADEL_TEST_PASSWORD: ${{ secrets.ZITADEL_TEST_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: |
          pnpx puppeteer browsers install chrome
      - run: pnpm install
      - name: Run test
        run: |
          for i in {1..3}; do
            echo "Attempt $i"
            if pnpm test:zitadel; then
              echo "Success on attempt $i"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
          done
          echo "All attempts failed"
          exit 1
